### ISSUE TITLE
Worker nodes never joined the cluster

### ISSUE THREAD

**Issue by galingit** [WillJCJ/eks-terraform-demo#4]
Hi guys, i'm trying to run your eks-terraform-demo code, but it never joined the worker nodes after I run:
`terraform output auth_config_map | kubectl apply -f -`
I have all the required IAM roles in AWS associated with the deployment user.
Any idea for troubleshooting?

**Comment by WillJCJ** [comment]
Hi Galin,

I threw this together a few days after AWS announced EKS. Kubernetes has gone up two versions since then and I'm sure EKS has gone through lots of iterations. It's likely that the permissions needed have changed or something in the UserData that sets up the worker nodes chould be different.

A much more comprehensive and up-to-date Terraform module can be found on the [official terraform-aws-modules GitHub](https://github.com/terraform-aws-modules/terraform-aws-eks). Hopefully you'll have more luck trying to apply that, sorry I couldn't be of much more help.
